### ISSUE TITLE
testValid() Error Check

### ISSUE THREAD

**Issue by aarr0n** [HenrikJoreteg/Happy.js#15]
If a field is required but empty and has already been earmarked as unhappy, it seems strange to then remove the error message on blur if the field if its still empty.

This :
if (required === true && val.length === 0) {

..seems to operate better than:
if (submit === true && required === true && val.length === 0) {

Curious what others thought...

**Comment by btpoe** [comment]
As of 439ddb2 error messages will persist until the field is valid.
