### ISSUE TITLE
Ability to Change Message Based on Test

### ISSUE THREAD

**Issue by aarr0n** [HenrikJoreteg/Happy.js#16]
It'll be great if the message displayed for a field could change based on the result of the test *and* if its required.

So for example if an email input is empty you'd display "field required", if its filled in but invalid display "valid email address required"... etc.

**Comment by willzablocki** [comment]
I also ran into a need for this feature.

**Comment by btpoe** [comment]
@wraithgar, What if we add the ability for a test to return a new Error? A test would look something like this:
```
$('#form').isHappy({
    fields: {
        '#birthday': {
            required: true,
            test: function() {
                if(isEmpty) {
                    return false;
                }
                if(isFuture) {
                    return new Error(‘Your birthday must have already happened.’);
                }
                if (isWednesday) {
                    return new Error(‘Your birthday cannot have happened on a Wednesday.’);
                }
                return true;
            },
            message: ‘Please provide a valid birth date.'
        }
    }
});
```

It should be pretty easy to implement. It wouldn't break backwards compatibility. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Browser_compatibility), Errors are supported in all versions of the major browsers.

**Comment by wraithgar** [comment]
The example looks good, not sure how we'd get that response into the errorEl given the current setup of the code though.

I agree this wouldn't break backwards compatibility either, cause we'd check if it were an error object or something before trying to parse it for a custom message, right?

**Comment by btpoe** [comment]
Correct, we'd have to tweak when/how the errorEl get's rendered, but by checking if the test response is an instance of Error, we should know how to handle the test.

**Comment by btpoe** [comment]
Custom error messages have been added as of [v0.9](https://github.com/HenrikJoreteg/Happy.js/releases/tag/v0.9).

The example above is a valid example of how test based messages work.
