### ISSUE TITLE
Better way to handle multiple test

### ISSUE THREAD

**Issue by wraithgar** [HenrikJoreteg/Happy.js#27]
If you want multiple tests on an input there should be a sensible way of doing that.  Currently the two approaches are:
- if test is a function call it, if it's an array of functions call them
- rethink how happy.methods works to allow some sort of chaining.

**Comment by Abhinav1217** [comment]
Can you show me an example on how you managed multiple tests. Currently I am doing the old way which is repetitive and bad looking code.

Upon reading your suggestion I first tried  my hands at the *Chaining Way* cause it is elegant and have a reusable approach, I use it in other modules in my project. But chaining needs to return its own object ( AFAIK ), so I couldn't get it to work on return true or false.

Then I tried calling array of functions .  

```
$(document).ready(function () {
	var hap = {
		test1 : function (val) { console.log("Called function test 1 ")},
		test2 : function (val) { console.log("Called function test 2 ")},
		test3 : function (val) { console.log("Called function test 3 ")},
		test4 : function (val) { console.log("Called function test 4 ")},
		test5 : function (val) { console.log("Called function test 5 ")}
	};
	$("#register form").isHappy({
		debug: true,
		submitButton: "#btn-register",
		fields: {

			"#User-Email" : {
				required: true,
				message : "User Email not correct",
				test : [hap.test1, hap.test2, hap.test3]

			},
		},

		happy : function () {
			console.log("I am Happy");
		},
		unHappy : function () {
			console.log("I am not Happy");
		}
	});
});
```

It doesn't work. Only `unHappy` method is called, No test was called.

**Comment by btpoe** [comment]
Do you still want to add support for this? As of v0.9, you could do the following:

```
$("#register").isHappy({
  fields: {
    "#userEmail" : {
      required: true,
      message: "Please provide a valid email address.",
      test: function(value) {
        if (!test1(value)) {
          return new Error('Test 1 failed.');
        }
        if (!test2(value)) {
          return new Error('Test 2 failed.');
        }
        if (!test3(value)) {
          return new Error('Test 3 failed.');
        }
        return true;
      }
    },
  },
});
```

If we were to run an array of tests, would they get their own message? If so, they would need to be an array of objects with a test and message for each.

**Comment by wraithgar** [comment]
That's still one test.  When this was written it was more about being able to say "these three predefined tests need to run" i.e. "must be longer than x characters" "must meet complexity guidelines" "must not contain carriage returns"  But this may be overthinking things and unless people are clamoring for it I'm just gonna close this.

**Comment by Abhinav1217** [comment]
In many scenarios multiple tests are really needed. For example, I have worked on an scheduling app, which is filled with form components, almost all of them require multiple tests. That was before I worked with Happy, so we had written about 60 functions which could be chained. and used the functions which we needed. 

What I am saying that at present, happy is perfect for simple registration form validation type of scenarios, But not suitable for JS Apps, which require a more complex set of test, `IF` blocks are good but does not provide Code re-usability. or proper modular structure.

**Comment by Abhinav1217** [comment]
In many scenarios multiple tests are really needed. For example, I have worked on an scheduling app, which is filled with form components, almost all of them require multiple tests. That was before I worked with Happy, so we had written about 60 functions which could be chained. and used the functions which we needed. 

What I am saying that at present, happy is perfect for simple registration form validation type of scenarios, But not suitable for JS Apps, which require a more complex set of test, `IF` blocks are good but does not provide Code re-usability. or proper modular structure.

**Comment by Abhinav1217** [comment]
In many scenarios multiple tests are really needed. For example, I have worked on an scheduling app, which is filled with form components, almost all of them require multiple tests. That was before I worked with Happy, so we had written about 60 functions which could be chained. and used the functions which we needed. 

What I am saying that at present, happy is perfect for simple registration form validation type of scenarios, But not suitable for JS Apps, which require a more complex set of test, `IF` blocks are good but does not provide Code re-usability. or proper modular structure.

**Comment by Abhinav1217** [comment]
In many scenarios multiple tests are really needed. For example, I have worked on an scheduling app, which is filled with form components, almost all of them require multiple tests. That was before I worked with Happy, so we had written about 60 functions which could be chained. and used the functions which we needed. 

What I am saying that at present, happy is perfect for simple registration form validation type of scenarios, But not suitable for JS Apps, which require a more complex set of test, `IF` blocks are good but does not provide Code re-usability. or proper modular structure.

**Comment by wraithgar** [comment]
Well there you go, I closed this prematurely.  Sorry about that.

**Comment by btpoe** [comment]
I wasn't saying this isn't a good idea, what I was trying to say was, if we don't account for how people will expect this to behave, we could be looking at a lot of issues filed.

If we add this support, inevitably, people are going to want custom error messages with this. Do we add that support out of the gate and force a convention like this:
```
test: [
  {
    test: tooShort,
    message: 'Please provide a username that is longer than 5 characters.'
  }, {
    test: singleLine,
    message: 'Your username cannot contain new lines.'
  }
]
```
or do we also provide the option to just pass an array of functions?
```
test: [ tooShort, singleLine ]
```
Would it be preferable for all tests to run and collect all the failures, or would it be better to stop after the first failed test?

I'm sure there are more questions that need answers, but these are the first that come to mind.

Sort of related; can either of you show how a test could both return the test results _and_ be chainable? I'm having a hard time wrapping my head around that.

**Comment by wraithgar** [comment]
```
Sort of related; can either of you show how a test could both return the test results and be chainable? I'm having a hard time wrapping my head around that.```

It would take quite a refactor of how the methods currently work, something to the effect where they are being passed and return some common state object, which feels like the wrong approach.  Those two ideas were really just brainstorms.

Now that tests can return an error object with a message, it seems like the 'array of tests' approach would be the one that isn't terribly difficult to implement, and is something that will be pretty easy to use and understand.

Your suggestion makes sense to me @btpoe

**Comment by btpoe** [comment]
I should mention that I do like the simplicity of passing an array of named functions. Should we aim to support all 3 or do you see that adding too much to a library that strives to be lightweight?

Also, I realize I'm going full-circle here, but someone could always return an error message out of each test. My only concern with that is that tests wouldn't be useful outside the realm of happy.js. I'm not sure if we want to worry about that or not.

**Comment by wraithgar** [comment]
I think simplicity is best, it should be an array of functions that work like errors currently do (return error if you want to customize message beyond the default for that input).  This leaves them as ordered/deterministic so we should stop after the first failure and error accordingly.

**Comment by btpoe** [comment]
The simple array and stopping after the first failure both sound good to me.

**Comment by Abhinav1217** [comment]
I would also prefer simple array of functions, stopping at first error.

**Comment by Abhinav1217** [comment]
All three methods would give developers nice flexibility options. But I would prefer keeping it a simple and lightweight solution. It can skip a few methods if it increases the size and complexity of happy.js .

**Comment by btpoe** [comment]
Alright, I just pushed 7c1fdc3cdd685556b7e7afebedbee4e2abd19ecd that adds support for multiple tests. Something we didn't talk about was the `arg` parameter. This is supposed to be passed in as a second argument to the test function. Leaving it a single value breaks down even for something as simple as needing a minLength and maxLength.

Here's how I'm handling the `arg` parameter:

- If the `test` parameter is a single function, the `arg` parameter will behave exactly as it used to. i.e:
  - A function will get evaluated and the returned value is what is passed to the `test`.
  - Any other type of value will get passed to the `test` as is.
- If the `test`parameter is an array of functions, the `arg` parameter will behave as follows:
  - A single function will get evaluated and the return value will be passed to all of the tests.
  - A single non-array value will get passed to all of the tests as is.
  - An array of values will map out in series to each test. If the particular index is a function, it will get evaluated and the returned value will be passed to that specific `test`.

Here is an example with some of the new possible scenarios:
```
$("#register").isHappy({
    fields: {
        '#just-like-before': {
            message: 'Field must be at least 3 characters.',
            test: happy.minLength,
            arg: 3
        },
        '#array-of-args-single-test': {
            message: 'Field must be either "this" or "that".',
            test: inArray,
            // this entire array will be passed to this test. as it would have before this recent feature addition
            arg: ['this', 'that']
        },
        '#arg-as-function-many-tests': {
            message: 'Please fill this field.',
            test: [isBeforeNow, isAfterNow],
            //  will pass the current time to all tests.
            arg: function() { return new Date(); }
        },
        '#array-of-args-array-of-tests': {
            message: 'Field must be a reasonable length.',
            test: [happy.minLength, happy.maxLength],
            // minLength will get a second arg of "3", maxLength will get a second arg of "32"
            arg: [3, 32]
        },
        '#arg-is-array-of-functions': {
            required: true,
            message: 'Please fill this field.',
            test: [matchesPassword, isAfterNow],
            // matchesPassword will get the value of $('#password'), isAfterNow will get the current date
            arg: [
                function() { return $('#password').val(); },
                function() { return new Date(); }
            ]
        }
    }
});
```

**Comment by Abhinav1217** [comment]
Downloading it now to test it. Will give you feedback in a few days. Thanks for this feature.

**Comment by wraithgar** [comment]
If this works, great, but part of me feels the arg approach is overwrought and we shout toss it out in favor of just a function that gets the field and nothing else.  Reusing these functions feels a bit clever and over-engineered, and if you want a 'min length' function just make a generator that accepts the value or something.

But changing *that* feels like a big change so idk, like I said if this works it works.

**Comment by wraithgar** [comment]
That works for me

**Comment by btpoe** [comment]
Updated.
