### ISSUE TITLE
better error handling from UX

### ISSUE THREAD

**Issue by introvert** [HenrikJoreteg/Happy.js#39]
Hello,

Thanks for this little-baby script. I really like it, however I don't like the way it handles displaying error messages. When I trigger submit button on the form and get error messages they disappear when I click any field. Instead they should disappear when the fields become valid.

Is there any way to improve that? Can you propose a simple solution?

Thanks

**Comment by adanarchila** [comment]
Actually is keyup, not onkeyup. But thanks @wraithgar your advice helped me. 

```
$('#loginAccount').isHappy({
    when: 'keyup',
    fields: {
        '#username': {
            required: true,
            message: 'enter your username'
        },
        '#password': {
            required: true,
            message: 'enter your password'
        }
    }
});
```

**Comment by btpoe** [comment]
As of 439ddb26e91d29436f5537a5bf6a0d357c3990f4 error messages will persist until the field is valid.
