### ISSUE TITLE
equal function

### ISSUE THREAD

**Issue by svanlint** [HenrikJoreteg/Happy.js#50]
Could someone please explain how to use the equal function in Happy.js to compare 2 password fields?

I can't seem to get this to work.

**Comment by goodmixer** [comment]
Trying to get this working also

**Comment by adanarchila** [comment]
I had no idea how to pass the second parameter to the equal function, so I did this:

```
$('#createAccount').isHappy({
    when: 'keyup',
    fields: {
        '#username': {
            required: true,
            message: 'required'
        },
        '#password': {
            required: true,
            message: 'required'
        },
        '#confirmPassword': {
            required: true,
            message: 'required',
            test: function() {
                return ($('#password').val() == $('#confirmPassword').val());
            }
        }
    }
});
```

**Comment by meyt** [comment]
Try to read documention: 
* arg (anything): An optional second argument that will get passed to the test function. This is useful for comparing with another paramter or whatnot. If this is a function it will be evaluated. This way you can compare it to something that is evaluated at runtime such as what they put in another field or to make a server call to check if a username is available, etc.

ReExample:
 
	$('#createAccount').isHappy({
		when: 'keyup',
		fields: {
			'#username': {
				required: true,
				message: 'required'
			},
			'#password': {
				required: true,
				message: 'required'
			},
			'#confirmPassword': {
				required: true,
				message: 'required',
				arg: function(){return $('#password').val();},
				test: happy.equal
			}
		}
	});

**Comment by btpoe** [comment]
Both solutions provided by @adanarchila and @meyt will get the job done.
