### ISSUE TITLE
Attribute selector does not work

### ISSUE THREAD

**Issue by terriann** [HenrikJoreteg/Happy.js#52]
Happyjs.com documentation states

    $('#awesomeForm').isHappy({
       fields: {
          // reference the field you're talking about, probably by `id`
          // but you could certainly do $('[name=name]') as well.
        [...]

The attribute selector comment is certainly not true. Using the following as a selector for the name field (exactly as the demo is formatted) throws errors:

            "[name='name']": {
              required: true,
              message: 'Might we inquire your name'
            },

            "[name=name]": {
              required: true,
              message: 'Might we inquire your name'
            },

            "name='name'": {
              required: true,
              message: 'Might we inquire your name'
            },

            "name=name": {
              required: true,
              message: 'Might we inquire your name'
            },

**Comment by RoelN** [comment]
@terriann Can't the ID simply be a random string? Replacing it with

    var error = {
        message: opts.message || '',
        id: selector.slice(1) + '_unhappy'
    };

with

    var error = {
        message: opts.message || '',
        id: Math.random().toString(36).slice(2)
    };

seems to work just as well. If the error message's ID needs to match the original input element's selector in some way, maybe a simple hash/encoding would suffice? E.g.

`id: selector.split("").map(function(x){ return x.charCodeAt(0).toString(16) }).join("")`

**Comment by btpoe** [comment]
#73 fixes this
