### ISSUE TITLE
Multiple error messages

### ISSUE THREAD

**Issue by Vinze** [HenrikJoreteg/Happy.js#60]
I was wondering, when validating an e-mail address I need to run multiple tests, and depending on the outcome the error message differs.

For example:

    $('#form').isHappy({
        fields: {
            '#email': {
                required: true,
                test: function(val) {
                    if (/^(?:\w+\.?\+?)*\w+@(?:\w+\.)+\w+$/.test(val)) {
                        $.post('/check-email', { email: val }, function(available) {
                            // message = E-mail address already taken!
                            return available;
                        });
                    } else {
                        // message = Not a valid e-mail address!
                        return false;
                    }
                },
                message: '*See test function*'
            }
        }
    });

Is this posible? If yes, how?

Thanks!

**Comment by btpoe** [comment]
Custom error messages have been added as of [v0.9](https://github.com/HenrikJoreteg/Happy.js/releases/tag/v0.9).

To change the error message, return an instance of `Error`. For example:
```
$('#form').isHappy({
    fields: {
        '#birthday': {
            required: true,
            test: function() {
                if(isEmpty) {
                    return false;
                }
                if(isFuture) {
                    return new Error(‘Your birthday must have already happened.’);
                }
                if (isWednesday) {
                    return new Error(‘Your birthday cannot have happened on a Wednesday.’);
                }
                return true;
            },
            message: ‘Please provide a valid birth date.'
        }
    }
});
```
