### ISSUE TITLE
handleSubmit

### ISSUE THREAD

**Issue by aleksander-tatskiy** [HenrikJoreteg/Happy.js#64]
Why not forwarding an event in arguments?

https://github.com/HenrikJoreteg/Happy.js/blob/master/happy.js#L39

I just want use in my custom code;
happy: function(event) {
                        event.preventDefault();
}

**Comment by btpoe** [comment]
Agreed as of cdffe8fa40aec4fb9f533668257bf6e3d71a78aa events are getting passed to happy / unHappy callbacks.
