### ISSUE TITLE
Validate loop increase as crazy...

### ISSUE THREAD

**Issue by potufel** [HenrikJoreteg/Happy.js#68]
Take your example fiele and:

1. Put this code:
console.log( 'Hello' )
in begining of method: 
field.testValid = function testValid(submit) {
// here put console.log('Hello')

2. Type something, i.g. "My name is" in <input> which is validatable
focus it and blur this input
and after that just click the document (not even form) and see console. 
Console counter of ('Hello') encrease all the time.

Append Jon to "My name is" and click on document 2 times - counter encrease 4 times;
Append Smith to "My name is Jon" and click on document - conter encerease 6 times ??
Erase the field - counter encrease all the time.

If it not work, just type something in Input and:
focus and blur it, 
focus and blur, 
click on document, 
focus and blur, 
click on document...
the counter should increase as a crazy!

It look's like "function testValid(submit) {}" fires once in the begining, but after that event fires several time on the same element.

I tested it on FF and chrome in Linux and windows 7.

Why?

**Comment by potufel** [comment]
I have found:
- a solution, but really don't know why it work :/ (on the end of this post)
- found bug, but I don't know where exactly. 
Sorry, I am not JS master.

                                                           -- BUG --
It looks like this event:
$(config.submitButton || this).bind('mousedown', handleMouseDown); 
or this events:
$(window).bind('mouseup', handleMouseUp);
$(window).bind('mouseup', field.testValid.bind(this));
fires one time only in the begining! It is OK, but... when you leave form and come back to field, the events are summing (accumulate) and fires not one, but event are fires 2, 4, 9, 16... times on ONE click (window click event?)

Try it yourself - just put this code:
console.log( 'Hello' )   inside (e.g. in the begining):
function testValid(submit) {}
and checkout how many times it is calling!

Do this:
- click one time on form element (e.g. fill input e-mail like 'aaaa')
- leave this input and click 1 time in document (anywhere)
Form element will be validate - ONE time! 
(Error occur: How are we to reach you sans email?? Console.log show "Hello" 1 time)
OK!

- back to the e-mail field (just click on it)
- and just leave this field (click anywhere)
Repeat it 10 times, and see the result how many times 'Hello' appear in console... 100 times!
So validator run 100 times!
Validator runs when you click on form element or this document $(window), so with 11 clicks on input nad 11 on document, it should validate 1 field 22 times - but no 100!

It looks like bind() method is cumulating (summing) events - but why?

Mayby this 2 code are wrong:
 $(window).bind('mouseup', handleMouseUp); 
$(window).bind('mouseup', field.testValid.bind(this));
and one of this invoke second ?? 
I really don know but...


                                                           -- SOLUTION --
Change this .bind() method:
$(window).bind('mouseup', handleMouseUp); 
to .one() method:
$(window).one('mouseup', handleMouseUp); 

That all.

**Comment by btpoe** [comment]
I noticed this issue too. 47a2922c9f1ab9390db838084cefb32ab8b3bfca resolves the issue you have documented here.
