### ISSUE TITLE
Text selection in input breaking after valid submit

### ISSUE THREAD

**Issue by tuckwilli** [HenrikJoreteg/Happy.js#70]
Example here. http://codepen.io/anon/pen/zGdJjp

After submitting a valid input, any mouseup event with the text input in focus will cause the cursor to move to the end of the input. I found that testValid and handlMouseUp were being called on every mouseup in the window after the submission. I fixed this in my own project by changing the event bindings for those two functions from 'bind' to 'one.'

**Comment by btpoe** [comment]
Fixed by 47a2922c9f1ab9390db838084cefb32ab8b3bfca. See http://codepen.io/btpoe/pen/dYjzav
